name: Generate Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake
        with:
          github_user_name: w3sll3y
          svg_out_path: github-contribution-grid-snake.svg
          
      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add github-contribution-grid-snake.svg
          git commit -m "Update snake.svg"
          git push
